### ISSUE TITLE
在linux中似乎不走环境变量指定的http_proxy和https_proxy代理服务器？

### ISSUE THREAD

**Issue by UntaggedRui** [PeterDing/aget-rs#5]
从v2ex中看到，之前用的是axel，尝试了一下ag。
发现在设置http_proxy和https_proxy代理服务器后，axel下载速度明显提升，但是ag没有反应。
ag能使用这样的代理模式吗

**Comment by PeterDing** [comment]
aget-rs 不能直接走代理，因为 [awc](https://github.com/actix/actix-web/tree/master/awc) 库目前不支持代理。

但是可以配合 [proxychains-ng](https://github.com/rofl0r/proxychains-ng) 来使用代理。

**Comment by UntaggedRui** [comment]
我也装了[proxychains-ng](https://github.com/rofl0r/proxychains-ng)这个，忘了用了。
那就用起来，OK。
